# Generated by Django 4.2.3 on 2023-07-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_bronmodel_station_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choicetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('08:00', '09:00'), ('09:00', '10:00'), ('10:00', '11:00'), ('11:00', '12:00'), ('12:00', '13:00'), ('13:00', '14:00'), ('14:00', '15:00'), ('15:00', '16:00'), ('16:00', '17:00'), ('17:00', '18:00'), ('18:00', '19:00'), ('19:00', '20:00'), ('20:00', '21:00'), ('21:00', '22:00'), ('22:00', '23:00'), ('23:00', '00:00'), ('00:00', '01:00')], max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='bronmodel',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='bronmodel',
            name='start_time',
        ),
    ]
